import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

/****** Layout  ******/
import Dashboard from '../layout/dashboard'
import Sidebar from '../layout/sidebar'
import Profile from '../layout/profile'
import Stack from '../layout/stack'
import Headers from '../layout/headers'
import Calendar from '../layout/calendar'

/****** Components  ******/
import CalendarUI from '../components/calendar/calendar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
          <Sidebar>
            <Profile/>
            <Stack />
          </Sidebar>
          <Dashboard>
            <Headers />
            <Calendar>
              <CalendarUI />
            </Calendar>
          </Dashboard>
      </div>
    </>
  )
}
